# Logistic Regression For Multiclass Classification Problem

In [1]:
# importing libraries
import pandas as pd 
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

In [5]:
# Creating dataset for multiclass classification
from sklearn.datasets import make_classification

X, y = make_classification(n_samples = 1000,
                           n_features = 10, 
                           n_classes = 3,
                           n_informative=3,
                           random_state=42)



In [6]:
# Independent features
X[:5]

array([[ 0.7715326 , -1.47433614,  2.19664605, -0.67899174,  0.76747934,
        -1.22617936, -0.23756628,  0.68174341,  1.08996189,  0.96250289],
       [ 1.85838284, -3.68087983,  0.22749588, -3.81836772,  0.63596775,
         1.60952067, -0.15313504, -0.47417818,  1.34113888, -0.77177196],
       [-0.98724764,  1.53916836,  0.5859042 ,  1.18528138, -0.73677014,
        -1.40681501,  0.68478283, -0.32202815, -1.45103394,  1.32543211],
       [-1.02241959,  1.3817867 ,  2.01527511,  0.86143427,  1.29064446,
        -1.88964929,  1.00913804,  0.36311563, -1.84423789,  0.31110999],
       [-0.13116121, -2.07900845,  1.48374391,  1.63685752, -0.7348109 ,
        -0.64015446,  2.66642175, -1.08574771, -0.89285099,  0.02979617]])

In [7]:
# Dependent Feature
y[:5]

array([1, 2, 1, 1, 2])

In [8]:
# Train Test Split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)
len(X_train), len(X_test), len(y_train), len(y_test)

(700, 300, 700, 300)

In [11]:
# Model Training
from sklearn.linear_model import LogisticRegression
from sklearn.multiclass import OneVsRestClassifier

# logistic = LogisticRegression(multi_class='ovr')  # this method is depreciated
# define the base binary classifier
base_model = LogisticRegression()

ovr_model = OneVsRestClassifier(base_model)
ovr_model.fit(X_train, y_train)
y_pred = ovr_model.predict(X_test)
y_pred[:5]


array([2, 0, 1, 2, 0])

In [13]:
# Performance Metrics
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Accuracy
score = accuracy_score(y_test, y_pred)
print(score)

# Confusion matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

# Classification report (precision, recall, f1-score)
print(classification_report(y_test, y_pred))

0.68
[[79 16  8]
 [31 38 27]
 [ 3 11 87]]
              precision    recall  f1-score   support

           0       0.70      0.77      0.73       103
           1       0.58      0.40      0.47        96
           2       0.71      0.86      0.78       101

    accuracy                           0.68       300
   macro avg       0.67      0.67      0.66       300
weighted avg       0.67      0.68      0.66       300



In [43]:
# Hyperparameter Tunning and Cross Validation
ovr_model = OneVsRestClassifier(LogisticRegression())
l1_ratio = [0, 1, 0.5]
c_values = [100.0, 10.0, 0.1, 0.01]
solver = ['lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga']


In [44]:
params = dict(estimator__l1_ratio=l1_ratio, estimator__C = c_values, estimator__solver = solver)

# GridSearchCV

In [45]:
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import StratifiedKFold
cv = StratifiedKFold()

grid = GridSearchCV(estimator=ovr_model, param_grid=params, scoring='accuracy', cv=cv)

In [46]:
grid

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=OneVsRestClassifier(estimator=LogisticRegression()),
             param_grid={'estimator__C': [100.0, 10.0, 0.1, 0.01],
                         'estimator__l1_ratio': [0, 1, 0.5],
                         'estimator__solver': ['lbfgs', 'liblinear',
                                               'newton-cg', 'newton-cholesky',
                                               'sag', 'saga']},
             scoring='accuracy')

In [53]:
# fit the data
grid.fit(X_train, y_train)

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=OneVsRestClassifier(estimator=LogisticRegression()),
             param_grid={'estimator__C': [100.0, 10.0, 0.1, 0.01],
                         'estimator__l1_ratio': [0, 1, 0.5],
                         'estimator__solver': ['lbfgs', 'liblinear',
                                               'newton-cg', 'newton-cholesky',
                                               'sag', 'saga']},
             scoring='accuracy')

In [54]:
# best params
grid.best_params_

{'estimator__C': 0.01, 'estimator__l1_ratio': 0, 'estimator__solver': 'lbfgs'}

In [55]:
# prediction
y_pred = grid.predict(X_test)

In [56]:
# performance metrics
# Accuracy
score = accuracy_score(y_test, y_pred)
print(score)

# Confusion matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

# Classification report(precision, recall, f1-score)
print(classification_report(y_test, y_pred))

0.6766666666666666
[[81 13  9]
 [36 32 28]
 [ 2  9 90]]
              precision    recall  f1-score   support

           0       0.68      0.79      0.73       103
           1       0.59      0.33      0.43        96
           2       0.71      0.89      0.79       101

    accuracy                           0.68       300
   macro avg       0.66      0.67      0.65       300
weighted avg       0.66      0.68      0.65       300

